### PR TITLE
Add macOS support for Jam

### PR DESCRIPTION
**Pull request by ganiskowicz**
Heyo!

After messing around with the app in order to get it running on Mac, I figured I'd implement the changes a bit more elegantly for anybody else who might want to do the same.

Things to note:
- Relative file pathing on Mac seems a bit different than Windows. While `file:///` would lead to the app directory on Windows, it would always always lead to the users root directory on Mac. Switching to `../` resolved the issue on Mac and did not effect the windows build. Similar platform dependant changes were made for the application path and other paths because of this.
- Created separate app.asar files depending on platform since `assets/osxapp.asar/config.js` (line 17) should be `pepflashplayer.dll` on Windows and `PepperFlashPlayer.plugin` on mac.
- Updated the icon.ico file to include a 512x512 version so the Mac app can build.
- Added an event handler in `assets/app.asar/index.js` (line 465) to ignore invalid certificates causing ERR_CERT_INVALID. I could not find another way to alleviate this issue, as the sub process doesn't seem to appreciate when electron calls execFile() on it, no matter what parameters are passed along with it.
- Mac users have to run the application as root in order to listen on port 443 and make changes within the app directory.
- Tested on my Mac and a Windows VM

### CODE REVIEW

**Comment by Sxip** [comment]
Great work! Thanks for making Mac support, really appreciate the effort! 🙌

**Comment by ganiskowicz** [comment]
No problem! In your next release make sure to include `Jam-mac.zip`. Not a big deal for now but it seems the app isn't able to automatically update without it.

**Comment by babylard** [comment]
This is sick.

**Comment by helpmewithanimaljam** [comment]
after i launch jam, it says i can't open animal jam because it is damaged. can someone help me?

**Comment by babylard** [comment]
> after i launch jam, it says i can't open animal jam because it is damaged. can someone help me?

The MacOS version?

**Comment by ganiskowicz** [comment]
> after i launch jam, it says i can't open animal jam because it is damaged. can someone help me?

Hey. I had this happen a couple times before making the pull request. The best I can tell you is to reinstall Animal Jam and launch Jam using the step by step guide in the MacOS docs #25. This is likely happening because you aren’t running the program as root, so any changes made in the Animal Jam app directory “damage” the application.

**Comment by helpmewithanimaljam** [comment]
I used the sudo command and downloaded a completely new version of aj and it STILL says that it's damaged. plz help

**Pull request merged**
